%% Import data from spreadsheet
function [DiffAssignmentL1] = Lab3Import
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/kevin/SkyDrive/KTH Work/Period 4
%    2014/GNSS/Labs/L3 - Computation of receiver position from
%    code and phase measurements/DiffAssignmentL1.xlsx Worksheet:
%    Blad1
%
% To extend the code for use with different selected data or a
% different spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2014/04/24 16:26:19

%% Import the data
[~, ~, raw] = xlsread('/Users/kevin/SkyDrive/KTH Work/Period 4 2014/GNSS/Labs/L3 - Computation of receiver position from code and phase measurements/DiffAssignmentL1.xlsx','Blad1');
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
DiffAssignmentL1 = reshape([raw{:}],size(raw));

%% Clear temporary variables
clearvars raw R;